### ISSUE TITLE
can not get processes on angular-js

### ISSUE THREAD

**Issue by bxf12315** [mswiderski/jbpm-examples#7]
I want to use you code https://github.com/mswiderski/jbpm-examples.
Follow steps
1 download BPMS 6.3
2 start business-central
 ./standalone.sh -c standalone-full.xml -Dorg.kie.server.user=kieserver -Dorg.kie.server.pwd=kieserver1!
3 start kie-server
 ./standalone.sh --server-config=standalone-full.xml -Djboss.socket.binding.port-offset=150  -Dorg.kie.server.id=first-kie-server  -Dorg.kie.server.location=http://localhost:8230/kie-server/services/rest/server -Dorg.kie.server.controller=http://localhost:8080/business-central/rest/controller  -Dorg.kie.server.controller.user=kieserver -Dorg.kie.server.controller.pwd=kieserver
4 config server template and add container on  business-central
5 deploy jbpm-angualr-js code in co-location of kie-server
6 login jbpm-angualr-js , 
  i can get all container , but i can not get other like process , process instance task.
 erro messge :"NetworkError: 404 Not Found - http://localhost:8230/kie-server/services/rest/server/queries/processes/definitions"
7 i watch you video https://www.youtube.com/watch?v=memwvmnBqvo 
   i find in containers page , miss a column action.
Please tell me , i miss which steps?
Thanks

**Comment by mswiderski** [comment]
that could mean that jbpm extension of kie server didn't start. Check server.log of kie server to see if it failed for whatever reason.
Additionally you can see if you can access this url: http://localhost:8230/kie-server/services/rest/server/queries/processes/definitions which I believe you won't

Make sure you have kie server of 6.3 version

**Comment by bxf12315** [comment]
Thanks.
It is work.
